<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: naturally_login.proto

namespace ApiGrpc\Naturally\Login;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>apiGrpc.naturally.login.LoginResponse</code>
 */
class LoginResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.service.login.User user = 1;</code>
     */
    protected $user = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Service\Login\User $user
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\NaturallyLogin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.service.login.User user = 1;</code>
     * @return \Service\Login\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>.service.login.User user = 1;</code>
     * @param \Service\Login\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Service\Login\User::class);
        $this->user = $var;

        return $this;
    }

}

