<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dcs.proto

namespace NaturallyGrpc\Dcs;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>NaturallyGrpc.Dcs.GetListDcsResponse</code>
 */
class GetListDcsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string code = 1;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>string message = 2;</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>string dcs = 3;</code>
     */
    protected $dcs = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $code
     *     @type string $message
     *     @type string $dcs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dcs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string code = 1;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dcs = 3;</code>
     * @return string
     */
    public function getDcs()
    {
        return $this->dcs;
    }

    /**
     * Generated from protobuf field <code>string dcs = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDcs($var)
    {
        GPBUtil::checkString($var, True);
        $this->dcs = $var;

        return $this;
    }

}

