<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dcs.proto

namespace NaturallyGrpc\Dcs;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>NaturallyGrpc.Dcs.GetListDcsRequest</code>
 */
class GetListDcsRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Dcs::initOnce();
        parent::__construct($data);
    }

}

