
module.exports.APP_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9k7INCN_gkvzJUlfo";
module.exports.CLIENT = {
    APP_CLIENT:{
        id:"7tG8xai2sU7BIMCIUzI1NiIsvzxxw",
        name:"APP_CLIENT",
        secret:"eovN9CnOiJIUzOn9m4ichcD3Wd"
    }
}
module.exports.ERROR_OBJ = {
    WRONG_USERNAME_PASSWORD:'WRONG_USERNAME_PASSWORD',
    SUSPENED_ACCOUNT:'SUSPENED_ACCOUNT' ,
    UNKNOW_ERROR:'UNKNOW_ERROR',
    CHI_NHANH_DUNG_HOAT_DONG:'CHI_NHANH_DUNG_HOAT_DONG',
    CHUA_CHON_CHI_NHANH:'CHUA_CHON_CHI_NHANH',
    SAI_CHI_NHANH:'SAI_CHI_NHANH',
    ERR_TRANG_QUAN_TRI_CUA_ADMIN:'ERR_TRANG_QUAN_TRI_CUA_ADMIN',
    ERR_ACCESS_TOKEN_REQUIRED:'ERR_ACCESS_TOKEN_REQUIRED',
    ERR_ACCESS_TOKEN_NOT_VALID :'ERR_ACCESS_TOKEN_NOT_VALID',
    ERR_PARSE_JSON:'ERR_PARSE_JSON',
    ERR_DONT_HAVE_PERMISSION:'ERR_DONT_HAVE_PERMISSION',
    ERR_EXPIRIED_TOKEN:'ERR_EXPIRIED_TOKEN',
    ERR_CLIENT_IS_NOT_VALID:'ERR_CLIENT_IS_NOT_VALID'
} 

