<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto

namespace GrpcApi\Login;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpcApi.login.LoginResponse</code>
 */
class LoginResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 code = 1;</code>
     */
    protected $code = 0;
    /**
     * Generated from protobuf field <code>string message = 2;</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>.grpcApi.login.LoginUserInfo loginUserInfo = 3;</code>
     */
    protected $loginUserInfo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $code
     *     @type string $message
     *     @type \GrpcApi\Login\LoginUserInfo $loginUserInfo
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Login::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.grpcApi.login.LoginUserInfo loginUserInfo = 3;</code>
     * @return \GrpcApi\Login\LoginUserInfo
     */
    public function getLoginUserInfo()
    {
        return $this->loginUserInfo;
    }

    /**
     * Generated from protobuf field <code>.grpcApi.login.LoginUserInfo loginUserInfo = 3;</code>
     * @param \GrpcApi\Login\LoginUserInfo $var
     * @return $this
     */
    public function setLoginUserInfo($var)
    {
        GPBUtil::checkMessage($var, \GrpcApi\Login\LoginUserInfo::class);
        $this->loginUserInfo = $var;

        return $this;
    }

}

