<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dcs.proto

namespace GPBMetadata;

class Dcs
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa0020a096463732e70726f746f12114e61747572616c6c79477270632e" .
            "44637322130a114765744c6973744463735265717565737422400a124765" .
            "744c697374446373526573706f6e7365120c0a04636f6465180120012809" .
            "120f0a076d657373616765180220012809120b0a03646373180320012809" .
            "32690a0a44637353657276696365125b0a0a4765744c6973744463731224" .
            "2e4e61747572616c6c79477270632e4463732e4765744c69737444637352" .
            "6571756573741a252e4e61747572616c6c79477270632e4463732e476574" .
            "4c697374446373526573706f6e7365220042360a1b696f2e677270632e65" .
            "78616d706c65732e68656c6c6f776f726c64420f48656c6c6f576f726c64" .
            "50726f746f5001a20203484c57620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

