<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto

namespace GPBMetadata;

class Login
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a82020a0b6c6f67696e2e70726f746f120d677270634170692e6c6f6769" .
            "6e22470a0d4c6f67696e55736572496e666f120a0a026964180120012805" .
            "120c0a046e616d65180220012809120d0a05656d61696c18032001280912" .
            "0d0a05464c504e6f180420012809222e0a0c4c6f67696e52657175657374" .
            "120f0a07757365725f6964180120012805120d0a05464c504e6f18022001" .
            "280922630a0d4c6f67696e526573706f6e7365120c0a04636f6465180120" .
            "012805120f0a076d65737361676518022001280912330a0d6c6f67696e55" .
            "736572496e666f18032001280b321c2e677270634170692e6c6f67696e2e" .
            "4c6f67696e55736572496e666f620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

