<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: naturally_login.proto

namespace GPBMetadata;

class NaturallyLogin
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\TestPackage::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0afc020a156e61747572616c6c795f6c6f67696e2e70726f746f12176170" .
            "69477270632e6e61747572616c6c792e6c6f67696e222f0a0c4c6f67696e" .
            "52657175657374120d0a05464c504e6f18012001280912100a0870617373" .
            "776f726418022001280922390a094c6f67696e55736572120f0a07757365" .
            "725f6964180120012805120c0a046e616d65180220012809120d0a05656d" .
            "61696c18032001280922320a0d4c6f67696e526573706f6e736512210a04" .
            "7573657218012001280b32132e736572766963652e6c6f67696e2e557365" .
            "72326a0a0e4e61747572616c6c794c6f67696e12580a054c6f67696e1225" .
            "2e617069477270632e6e61747572616c6c792e6c6f67696e2e4c6f67696e" .
            "526571756573741a262e617069477270632e6e61747572616c6c792e6c6f" .
            "67696e2e4c6f67696e526573706f6e7365220042360a1b696f2e67727063" .
            "2e6578616d706c65732e68656c6c6f776f726c64420f48656c6c6f576f72" .
            "6c6450726f746f5001a20203484c57620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

