<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: naturally.proto

namespace GPBMetadata;

class Naturally
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Auth::initOnce();
        \GPBMetadata\Users::initOnce();
        \GPBMetadata\Dcs::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a690a0f6e61747572616c6c792e70726f746f1a0b75736572732e70726f" .
            "746f1a096463732e70726f746f42360a1b696f2e677270632e6578616d70" .
            "6c65732e68656c6c6f776f726c64420f48656c6c6f576f726c6450726f74" .
            "6f5001a20203484c57620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

